cart/urls.py
from django.urls import path
from cart.views import *

app_name = "cart"

urlpatterns = [
    path("", detail, name="detail"),
    path("add/<int:product_id>", add, name="product_add"),
    path("remove/<product_id>", remove, name="product_remove"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("accounts/", include("allauth.urls")),
    path("dogs/", include("dogs.urls")),
    path("photo/", include("photo.urls")),
    path("shop/", include("shop.urls")),
    path("shop/cart", include("cart.urls")),
    path("shop/coupon/", include("coupon.urls")),
    path("shop/order/", include("order.urls")),
]

coupon/urls.py
from django.urls import path
from coupon.views import add_coupon

app_name = "coupon"

urlpatterns = [
    path("add/", add_coupon, name="add"),
]

order/urls.py
from django.urls import path
from order.views import *

app_name = "orders"

urlpatterns = [
    path("create/", order_create, name="order_create"),
    path("create_ajax/", OrderCreateAjaxView.as_view(), name="order_create_ajax"),
    path("checkout/", OrderCheckoutAjaxView.as_view(), name="order_checkout"),
    path("validation/", OrderImpAjaxView.as_view(), name="order_validation"),
    path("complete/", order_complete, name="order_complete"),
    path("admin/order//<int:order_id>/", admin_order_detail, name="admin_order_detail"),
    # path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path, re_path
from .views import *

app_name = "shop"

urlpatterns = [
    path("", product_in_category, name="product_all"),
    # re_path(r'^(?P<category_slug>[^/]+(?u))/$', product_in_category, name='product_in_category'),
    path("<category_slug>/", product_in_category, name="product_in_category"),
    path("<int:id>/<product_slug>/", product_detail, name="product_detail"),
    path("my/orders/", myorders, name="myorders"),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


class AddProductForm(forms.Form):
    quantity = forms.IntegerField()
    is_update = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )

coupon/forms.py
from django import forms


class AddCouponForm(forms.Form):
    code = forms.CharField(label="Your Coupon Code")

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required

from shop.models import Product
from cart.forms import AddProductForm
from cart.cart import Cart
from coupon.forms import AddCouponForm


@require_POST
def add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = AddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd["quantity"], is_update=cd["is_update"])

    return redirect("cart:detail")


def remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:detail")


@login_required
def detail(request):
    cart = Cart(request)
    add_coupon = AddCouponForm()

    for product in cart:
        product["quantity_form"] = AddProductForm(
            initial={"quantity": product["quantity"], "is_update": True}
        )

    return render(request, "cart/detail.html", {"cart": cart, "add_coupon": add_coupon})

cart/templates/cart/detail.html
{% extends 'shopbase.html' %} {% load static %} {% load humanize %} {% block title %}
  - 장바구니
{% endblock %} {% block content %}
  <div class="container">
    <br /><br />
    <h2 align="center" style="font-weight: 600; font-size: 40px; font-family: 'Binggrae-Bold'">
      <i style="color: #9b7cc9" class="fas fa-cart-arrow-down"></i>&nbsp;
      장바구니
    </h2>
    <br />
    <table class="table table-striped">
      <thead style="font-weight: 600; font-family: 'Nanum Gothic', sans-serif">
        <tr style="
                    font-weight: 600;
                    font-family: 'Nanum Gothic', sans-serif;
                " align="center">
          <th scope="col" width="300">제품 사진</th>
          <th scope="col" width="320">제품 명</th>
          <th scope="col" width="20%">수량</th>
          <th scope="col">제거</th>
          <th scope="col">개당 가격</th>
          <th scope="col">총 가격</th>
        </tr>
      </thead>

      <tbody style="font-family: 'SeoulNamsanM'; font-size: 16px">
        {% for item in cart %}
          {% with product = item.product %}
            <tr align="center">
              <th scope="row">
                <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" style="border-radius: 10px; width: 50%" class="img-thumbnail" /></a>
              </th>

              <td style="font-weight: 600">{{ product.name }}</td>

              <td>
                <form action="{% url 'cart:product_add' product.id %}" method="post">
                  {{ item.quantity_form.quantity }} {{ item.quantity_form.is_update }}
                  <input type="submit" class="btn btn-light roundop" value="변경" />
                  {% csrf_token %}
                </form>
              </td>

              <td>
                <a href="{% url 'cart:product_remove' product.id %}">Remove</a>
              </td>

              <td class="num">{{ item.price|floatformat:'0'|intcomma }}원</td>
              <td class="num">{{ item.total_price|floatformat:'0'|intcomma }}원</td>
            </tr>
          {% endwith %}
        {% endfor %} {% if cart.coupon %}
          <tr class="subtotal">
            <td>총 금액</td>
            <td colspan="4"></td>
            <td>{{ cart.get_product_total|floatformat:'0'|intcomma }}원</td>
          </tr>
          <tr>
            <td>
              "{{ cart.coupon.code }}" 쿠폰 사용<!-- - ￦{{ cart.coupon.amount|floatformat:"0"|intcomma }} -->
            </td>
            <td colspan="4"></td>
            <td>{{ cart.get_discount_total|floatformat:'0'|intcomma }}원 할인</td>
          </tr>
        {% endif %}
        <tr class="total" style="font-size: 18px; font-weight: 600">
          <td>최종 결제금액</td>
          <td colspan="4"></td>
          <td class="num">{{ cart.get_total_price|floatformat:'0'|intcomma }}원</td>
        </tr>
      </tbody>
    </table>
    <div class="container" style="font-family: 'SeoulNamsanM'; font-size: 16px">
      <form action="{% url 'coupon:add' %}" method="post">
        <label for="id_code">쿠폰 번호 :</label>
        <input type="text" name="code" required="" id="id_code" class="roundop" />
        <input type="submit" class="btn btn-success" value="사용" />
        {% csrf_token %}
      </form>
      <hr />
      <!--   <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">￦{{ cart.get_product_total|floatformat:"0"|intcomma }}</td>
            </tr>   -->

      <p class="text-right">
        <a href="{% url 'shop:product_all' %}" class="btn btn-secondary">계속 쇼핑하기</a>
        <a href="{% url 'orders:order_create' %}" style="width: 120px; height: 38px" class="btn movebtn">주문하기</a>
      </p>
    </div>
  </div>
  <br /><br />
{% endblock %}