cart/urls.py
from django.urls import path
from cart.views import *

app_name = "cart"

urlpatterns = [
    path("", detail, name="detail"),
    path("add/<int:product_id>", add, name="product_add"),
    path("remove/<product_id>", remove, name="product_remove"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("accounts/", include("allauth.urls")),
    path("dogs/", include("dogs.urls")),
    path("photo/", include("photo.urls")),
    path("shop/", include("shop.urls")),
    path("shop/cart", include("cart.urls")),
    path("shop/coupon/", include("coupon.urls")),
    path("shop/order/", include("order.urls")),
]

dogs/urls.py
from django.urls import path, re_path
from dogs.views import *
from dogs.models import *
from django.views.generic.detail import DetailView


app_name = "dogs"

urlpatterns = [
    path("info/", info_list, name="info_list"),
    path("infocreate/", infoCreate.as_view(), name="info_create"),
    path("info/update/<int:pk>/", infoUpdate.as_view(), name="info_update"),
    path("info/delete/<int:pk>/", infoDelete.as_view(), name="info_delete"),
    path("daily/", daily_list, name="daily_list"),
    path("dailycreate/", dailyCreate.as_view(), name="daily_create"),
    path("daily/update/<int:pk>/", dailyUpdate.as_view(), name="daily_update"),
    path("daily/delete/<int:pk>/", dailyDelete.as_view(), name="daily_delete"),
    path("daily/detail/<int:pk>/", dailyDetail.as_view(), name="daily_detail"),
    # re_path(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list_daily'),
    re_path(
        r"^tag/(?P<tag>[^/]+)/$", PostTOL.as_view(), name="tagged_object_list_daily"
    ),
    path("chart/", chartt, name="chart"),
]

dogs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from tagging.fields import TagField


class mydogs(models.Model):
    # user.id 를 받아와
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_dogs")

    # 강아지 세부정보 입력필드
    names = models.CharField(max_length=100)
    dogpic = models.ImageField(
        upload_to="photos/%Y/%m/%d", default="photos/no_image.png"
    )
    birth = models.DateField(blank=True, null=True)
    weight = models.DecimalField(max_digits=10, decimal_places=2)
    species = models.CharField(max_length=50)
    registernumber = models.IntegerField()

    # 중성화
    gender = models.CharField(max_length=15)
    neutral = models.BooleanField()

    # 예방접종 필드
    dhppl = models.DateField(blank=True, null=True)
    corona = models.DateField(blank=True, null=True)
    kennel = models.DateField(blank=True, null=True)
    rabies = models.DateField(blank=True, null=True)
    heartworm = models.DateField(blank=True, null=True)

    # 정보 작성 일자 및 업데이트 날짜 표기
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated"]

    def __str__(self):
        return self.owner.username + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")

    def get_absolute_url(self):
        return reverse("/", args=[str(self.id)])


class daily(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_daily")

    names = models.CharField(max_length=100)

    # 일기 주요부분
    walkcount = models.IntegerField()
    walktime = models.TimeField(blank=True, null=True)
    foodamount = models.DecimalField(max_digits=10, decimal_places=2)
    snackcount = models.DecimalField(max_digits=10, decimal_places=2)

    # 임의 작성 필드
    remarks = models.TextField(blank=True, null=True)
    statustrace = models.TextField(blank=True, null=True)

    # 정보 작성 일자 및 업데이트 날짜 표기
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    tag = TagField()

    class Meta:
        ordering = ["-updated"]

        def __str__(self):
            return (
                self.owner.username + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")
            )

dogs/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView
from dogs.models import *
from django.contrib.auth.decorators import login_required
from tagging.views import TaggedObjectList
from django.db.models import Sum, Avg, Count, Subquery
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
    PermissionRequiredMixin,
    AccessMixin,
)


@login_required
def info_list(request):
    # mydog 에서 objects 필터를, owner 필드를 request 받은 user 로 적용.
    # 로그인 한 이용자의 mydogs object 만 return
    infos = mydogs.objects.filter(owner=request.user)

    return render(request, "dogs/infolist.html", {"infos": infos})


class infoCreate(LoginRequiredMixin, CreateView):
    model = mydogs
    fields = [
        "names",
        "dogpic",
        "birth",
        "weight",
        "species",
        "gender",
        "neutral",
        "registernumber",
        "dhppl",
        "corona",
        "kennel",
        "rabies",
        "heartworm",
    ]
    template_name = "dogs/infocreate.html"

    def form_valid(self, form):
        form.instance.owner_id = self.request.user.id
        # 입력한 값들을 검증 한 후 에러가 없다면 하단 if 문 실행 (DB 저장)
        if form.is_valid():
            form.instance.save()
            return redirect("/dogs/info/")
        else:
            return self.render_to_response({"form": form})


class infoUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = mydogs
    success_url = "/dogs/info/"
    fields = [
        "names",
        "dogpic",
        "birth",
        "weight",
        "species",
        "gender",
        "neutral",
        "registernumber",
        "dhppl",
        "corona",
        "kennel",
        "rabies",
        "heartworm",
    ]
    template_name = "dogs/infoupdate.html"

    def test_func(self):
        obj = self.get_object()
        return obj.owner == self.request.user


class infoDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = mydogs
    success_url = "/dogs/info/"
    template_name = "dogs/infodelete.html"

    def test_func(self):
        obj = self.get_object()
        return obj.owner == self.request.user


class PostTOL(LoginRequiredMixin, TaggedObjectList):
    model = daily
    template_name = "dogs/taglist.html"


@login_required
def daily_list(request):
    daily_list = daily.objects.filter(owner=request.user)
    paginator = Paginator(daily_list, 30)  # Show 20 contacts per page

    page = request.GET.get("page")

    try:
        dailys = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        dailys = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        dailys = paginator.page(paginator.num_pages)

    return render(request, "dogs/dailylist.html", {"dailys": dailys})


class dailyCreate(LoginRequiredMixin, CreateView):
    model = daily
    fields = [
        "names",
        "walkcount",
        "walktime",
        "foodamount",
        "snackcount",
        "remarks",
        "statustrace",
        "tag",
    ]
    template_name = "dogs/dailycreate.html"

    def form_valid(self, form):
        form.instance.owner_id = self.request.user.id
        # 입력한 값들을 검증 한 후 에러가 없다면 하단 if 문 실행 (DB 저장)
        if form.is_valid():
            form.instance.save()
            return redirect("/dogs/daily/")
        else:
            return self.render_to_response({"form": form})


class dailyDetail(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = daily
    template_name = "dogs/dailydetail.html"

    def test_func(self):
        obj = self.get_object()
        return obj.owner == self.request.user


class dailyUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = daily
    fields = [
        "names",
        "walkcount",
        "walktime",
        "foodamount",
        "snackcount",
        "remarks",
        "statustrace",
        "tag",
    ]
    template_name = "dogs/dailyupdate.html"
    success_url = "/dogs/daily/"

    def test_func(self):
        obj = self.get_object()
        return obj.owner == self.request.user


class dailyDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = daily
    success_url = "/"
    template_name = "dogs/dailydelete.html"

    def test_func(self):
        obj = self.get_object()
        return obj.owner == self.request.user


@login_required
def chartt(request):
    ##### 견종별 몸무게 및 숫자 #####

    # 대형
    afghanAVG = mydogs.objects.filter(species="Afghan Hound").aggregate(
        Avg("weight"), Count("species")
    )
    pitbullAVG = mydogs.objects.filter(species="American Pitbull Terrier").aggregate(
        Avg("weight"), Count("species")
    )
    bloodAVG = mydogs.objects.filter(species="Bloodhound").aggregate(
        Avg("weight"), Count("species")
    )
    chowAVG = mydogs.objects.filter(species="Chow Chow").aggregate(
        Avg("weight"), Count("species")
    )
    dalmatianAVG = mydogs.objects.filter(species="Dalmatian").aggregate(
        Avg("weight"), Count("species")
    )
    dutchAVG = mydogs.objects.filter(species="Dutch Shepherd").aggregate(
        Avg("weight"), Count("species")
    )
    englishAVG = mydogs.objects.filter(species="English Foxhound").aggregate(
        Avg("weight"), Count("species")
    )
    gershepherdAVG = mydogs.objects.filter(species="German Shepherd").aggregate(
        Avg("weight"), Count("species")
    )
    goldadorAVG = mydogs.objects.filter(species="Goldador").aggregate(
        Avg("weight"), Count("species")
    )
    goldenAVG = mydogs.objects.filter(species="Golden Retriever").aggregate(
        Avg("weight"), Count("species")
    )
    daneAVG = mydogs.objects.filter(species="Great Dane").aggregate(
        Avg("weight"), Count("species")
    )
    pyreneesAVG = mydogs.objects.filter(species="Great Pyrenees").aggregate(
        Avg("weight"), Count("species")
    )
    houndAVG = mydogs.objects.filter(species="Greyhound").aggregate(
        Avg("weight"), Count("species")
    )
    samoyedAVG = mydogs.objects.filter(species="Samoyed").aggregate(
        Avg("weight"), Count("species")
    )
    huskyAVG = mydogs.objects.filter(species="Siberian Husky").aggregate(
        Avg("weight"), Count("species")
    )
    airedaleAVG = mydogs.objects.filter(species="Airedale Terrier").aggregate(
        Avg("weight"), Count("species")
    )
    appenzellerAVG = mydogs.objects.filter(species="Appenzeller Sennenhund").aggregate(
        Avg("weight"), Count("species")
    )
    bulldogAVG = mydogs.objects.filter(species="Bulldog").aggregate(
        Avg("weight"), Count("species")
    )
    bigAVG = mydogs.objects.filter(
        species="Afghan Hound"
        and "American Pitbull Terrier"
        and "Bloodhound"
        and "Bulldog"
        and "Chow Chow"
        and "Dalmatian"
        and "Dutch Shepherd"
        and "English Foxhound"
        and "Appenzeller Sennenhund"
        and "German Shepherd"
        and "Goldador"
        and "Golden Retriever"
        and "Great Dane"
        and "Great Pyrenees"
        and "Greyhound"
        and "Samoyed"
        and "Siberian Husky"
        and "Airedale Terrier"
    ).aggregate(Avg("weight"), Count("species"))

    # 중형
    eskimoAVG = mydogs.objects.filter(species="American Eskimo Dog").aggregate(
        Avg("weight"), Count("species")
    )
    cockerAVG = mydogs.objects.filter(species="Cocker Spaniel").aggregate(
        Avg("weight"), Count("species")
    )
    corgiAVG = mydogs.objects.filter(species="Pembroke Welsh Corgi").aggregate(
        Avg("weight"), Count("species")
    )
    borderAVG = mydogs.objects.filter(species="Border Collie").aggregate(
        Avg("weight"), Count("species")
    )
    pinscherAVG = mydogs.objects.filter(species="German Pinscher").aggregate(
        Avg("weight"), Count("species")
    )
    middleAVG = mydogs.objects.filter(
        species="American Eskimo Dog"
        and "German Pinscher"
        and "Border Collie"
        and "Cocker Spaniel"
        and "Pembroke Welsh Corgi"
    ).aggregate(Avg("weight"), Count("species"))

    # 소형
    australianAVG = mydogs.objects.filter(species="Australian Terrier").aggregate(
        Avg("weight"), Count("species")
    )
    beagleAVG = mydogs.objects.filter(species="Beagle").aggregate(
        Avg("weight"), Count("species")
    )
    bichonAVG = mydogs.objects.filter(species="Bichon Frise").aggregate(
        Avg("weight"), Count("species")
    )
    bostonAVG = mydogs.objects.filter(species="Boston Terrier").aggregate(
        Avg("weight"), Count("species")
    )
    chiAVG = mydogs.objects.filter(species="Chihuahua").aggregate(
        Avg("weight"), Count("species")
    )
    dachhundAVG = mydogs.objects.filter(species="Dachshund").aggregate(
        Avg("weight"), Count("species")
    )
    poodleAVG = mydogs.objects.filter(species="Poodle").aggregate(
        Avg("weight"), Count("species")
    )
    pugAVG = mydogs.objects.filter(species="Pug").aggregate(
        Avg("weight"), Count("species")
    )
    tzuAVG = mydogs.objects.filter(species="Shih Tzu").aggregate(
        Avg("weight"), Count("species")
    )
    yorkAVG = mydogs.objects.filter(species="Yorkshire Terrier").aggregate(
        Avg("weight"), Count("species")
    )
    malteseAVG = mydogs.objects.filter(species="Maltese").aggregate(
        Avg("weight"), Count("species") and Count("species")
    )
    pomeAVG = mydogs.objects.filter(species="Pomeranian").aggregate(
        Avg("weight"), Count("species")
    )
    smallAVG = mydogs.objects.filter(
        species="Australian Terrier"
        and "Beagle"
        and "Bichon Frise"
        and "Boston Terrier"
        and "Chihuahua"
        and "Dachshund"
        and "Poodle"
        and "Pug"
        and "Shih Tzu"

dogs/templates/dogs/dailycreate.html
{% extends 'base.html' %} {% block title %}
  - 일일정보 기록
{% endblock %} {% block content %}
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default" style="font-family: 'Poor Story', cursive; font-size: 20px">
      <form action="" method="post" enctype="multipart/form-data">
        <br />
        <h2 align="center"><i class="fas fa-thumbtack"></i> 일일 정보 기록하기</h2>
        <br />
        <p>
          <label for="id_names"><i class="fas fa-signature"></i> 이름 :</label>
          <input class="roundop" type="text" name="names" maxlength="100" required="" id="id_names" />
        </p>

        <p>
          <label for="id_walkcount"><i class="fas fa-walking"></i> 산책 횟수 :</label>
          <input class="roundop" type="number" name="walkcount" required="" id="id_walkcount" />
        </p>
        <p>
          &emsp;▷ 10분이라도 좋습니다! 하루에 산책을 나간 횟수를 기록해주세요.<br />
          &emsp;▷ 1일 1산책은 기본인거 아시죠~?
        </p>

        <p>
          <label for="id_walktime"><i class="fas fa-hourglass-half"></i> 산책시간 :</label>
          <input class="roundop" type="time" name="walktime" id="id_walktime" value="00:00" />
        </p>
        <p>
          &emsp;▷ 산책 나간 총 시간을 더해서 기록해주세요.<br />
        </p>

        <p>
          <label for="id_foodamount"><i class="fas fa-bone"></i> 사료 배급량 :</label>
          <input class="roundop" type="number" name="foodamount" step="0.01" required="" id="id_foodamount" />gram
        </p>
        <p>
          &emsp;▷ 하루 사료 급여랑을 '그램' 단위로 기록해주세요.<br />
          &emsp;▷ 소수점 둘째 자리까지 기록 가능합니다. (ex. 253.85 gram)
        </p>

        <p>
          <label for="id_snackcount"><i class="fas fa-cookie-bite"></i> 간식 배급횟수 :</label>
          <input class="roundop" type="number" name="snackcount" step="0.01" required="" id="id_snackcount" />
        </p>
        <p>
          &emsp;▷ 하루에 간식을 몇개 급여했는지 기록해주세요.<br />
          &emsp;▷ 1개 기준은 간식별 낱개 수량 혹은 기준을 정하기 어려울 경우,<br />
          &emsp;&emsp;기존에 급여하던 간식량과 비교하여 기록해주세요<br />
          &emsp;▷ 간식 및 사료량 비교차트는 자신에게만 보여집니다.
        </p>

        <br />
        <hr />
        <br />
        <h3 align="center"><i class="far fa-comment-dots"></i> 추가 정보</h3>
        <br />

        <p>
          <label for="id_remarks"><i class="far fa-bell"></i> 특이사항 :</label>
          <textarea class="roundop" name="remarks" rows="4" id="id_remarks" style="width: 100%"></textarea>
        </p>
        <p>
          &emsp;▷ 당일의 특이사항에 대해 기록해주세요.<br />
          &emsp;▷ 일기 형태로 기록하셔도 좋고, 당일 반려견에 대해 짤막하게 기록해주셔도 좋습니다.
        </p>

        <p>
          <label for="id_statustrace"><i class="fas fa-asterisk"></i> 상태추적 :</label>
          <textarea class="roundop" name="statustrace" rows="3" id="id_statustrace" style="width: 100%"></textarea>
        </p>
        <p>
          &emsp;▷ 특정한 상태 추적이 필요할때 계속해서 상태를 추적하기위해 상황별 변화를 기록해주세요.<br />
          &emsp;▷ 이상증상이 의심되거나 기록이 필요할때 참고해서 이용하시면 좋습니다.
        </p>

        <p>
          <label for="id_tag"><i class="fas fa-tag"></i> 태그 :</label>
          <input class="roundop" type="text" name="tag" maxlength="255" id="id_tag" />
        </p>
        <p>
          &emsp;▷ 태그 란을 통해서 손쉽게 해당 게시글을 찾을 수 있게 하세요!<br />
          &emsp;▷ 상태 추적시 의심부위나 특이사항의 중점단어를 기록해주면 유용하게 사용하실수 있습니다.<br />
          &emsp;▷ ex. 산책X, 사료많이줌, 슬개골의심, 검진<br />
          &emsp;▷ 작성요령 : 각 태그는 ( , ) 로 구분되며 ( # ) 을 추가로 입력할 필요가 없습니다.
        </p>

        {% csrf_token %}
        <div align="center">
          <br /><button type="submit" class="btn raise"><i class="far fa-check-square"></i> 입력 완료</button>&emsp;
          <button type="reset" class="btn raise" style="color: red"><i class="far fa-window-close"></i> 다시 작성</button>
        </div>
        <br />
      </form>
    </div>
  </div>
  <br /><br />
{% endblock %}

dogs/templates/dogs/dailydelete.html
{% extends 'base.html' %} {% block title %}
  - Delete
{% endblock %} {% block style %}
  #footer { position: absolute; bottom: 0; width: 1110px; }
{% endblock %} {% block content %}
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default" align="center">
      <br /><br /><br /><br /><br /><br />
      <div class="alert alert-info">
        정말 "{{ object.names }}"의<br />
        {{ object.updated }} 기록을 지우시겠습니까??
      </div>
      <form action="" method="post">
        {{ form.as_p }} {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="삭제" />
      </form>
    </div>
    <div class="col-md-2"></div>
  </div>
{% endblock %}

dogs/templates/dogs/infocreate.html
{% extends 'base.html' %} {% block title %}
  - 기본정보 작성
{% endblock %} {% block content %}
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default" style="font-family: 'Poor Story', cursive; font-size: 20px">
      <br />
      <h1 align="center">내 반려견 정보 입력</h1>
      <br /><br />

      <h3><i class="fas fa-dog fa-lg"></i> 기본 정보</h3>
      <br />
      <form action="" method="post" enctype="multipart/form-data">
        <p>
          <label for="id_names">이름 :</label>
          <input class="roundop" type="text" name="names" maxlength="100" required="" id="id_names" style="
                        background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABHklEQVQ4EaVTO26DQBD1ohQWaS2lg9JybZ+AK7hNwx2oIoVf4UPQ0Lj1FdKktevIpel8AKNUkDcWMxpgSaIEaTVv3sx7uztiTdu2s/98DywOw3Dued4Who/M2aIx5lZV1aEsy0+qiwHELyi+Ytl0PQ69SxAxkWIA4RMRTdNsKE59juMcuZd6xIAFeZ6fGCdJ8kY4y7KAuTRNGd7jyEBXsdOPE3a0QGPsniOnnYMO67LgSQN9T41F2QGrQRRFCwyzoIF2qyBuKKbcOgPXdVeY9rMWgNsjf9ccYesJhk3f5dYT1HX9gR0LLQR30TnjkUEcx2uIuS4RnI+aj6sJR0AM8AaumPaM/rRehyWhXqbFAA9kh3/8/NvHxAYGAsZ/il8IalkCLBfNVAAAAABJRU5ErkJggg==');
                        background-repeat: no-repeat;
                        background-attachment: scroll;
                        background-size: 16px 18px;
                        background-position: 98% 50%;
                    " />
        </p>

        <p>
          <label for="id_dogpic">사진 :</label>
          <input class="roundop" type="file" name="dogpic" accept="image/*" id="id_dogpic" />
        </p>

        <p>
          <label for="id_birth">태어난 날 :</label>
          <input class="roundop" type="date" name="birth" id="id_birth" />
        </p>

        <p>
          <label for="id_weight">몸무게 :</label>
          <input class="roundop" type="number" name="weight" step="0.01" required="" id="id_weight" />kg(.00 까지 입력가능)
        </p>

        <p>
          <label for="id_species">
            종 :<select class="roundop" name="species" id="id_species">
              <optgroup label="대형">
                <option value="Afghan Hound">아프간 하운드</option>
                <option value="American Pitbull Terrier">아메리칸 핏불 테리어</option>
                <option value="Bloodhound">블러드하운드</option>
                <option value="Border Collie">보더 콜리</option>
                <option value="Chow Chow">차우 차우</option>
                <option value="Dalmatian">달마시안</option>
                <option value="Dutch Shepherd">더치 셰퍼드</option>
                <option value="English Foxhound">잉글리시 폭스하운드</option>
                <option value="German Pinscher">저먼 핀셔</option>
                <option value="German Shepherd">저먼 셰퍼드</option>
                <option value="Goldador">골다도</option>
                <option value="Golden Retriever">골든 리트리버</option>
                <option value="Great Dane">그레이트 데인</option>
                <option value="Great Pyrenees">그레이트 피레니즈</option>
                <option value="Greyhound">그레이하운드</option>
                <option value="Samoyed">사모예드</option>
                <option value="Siberian Husky">시베리안 허스키</option>
                <option value="Crossbreeds">혼종</option>
              </optgroup>
              <optgroup label="중형">
                <option value="Airedale Terrier">에어데일 테리어</option>
                <option value="American Eskimo Dog">아메리칸 에스키모</option>
                <option value="Appenzeller Sennenhund">아펜젤러 세넨훈드</option>
                <option value="Bulldog">불독</option>
                <option value="Cocker Spaniel">코커 스파니엘</option>
                <option value="Pembroke Welsh Corgi">펨브록 웰시 코기</option>
                <option value="Crossbreeds">혼종</option>
              </optgroup>
              <optgroup label="소형">
                <option value="Australian Terrier">오스트레일리안 테리어</option>
                <option value="Beagle">비글</option>
                <option value="Bichon Frise">비숑 프리제</option>
                <option value="Boston Terrier">보스턴 테리어</option>
                <option value="Chihuahua">치와와</option>
                <option value="Dachshund">닥스훈트</option>
                <option value="Poodle">푸들</option>
                <option value="Pug">퍼그</option>
                <option value="Shih Tzu">시츄</option>
                <option value="Yorkshire Terrier">요크셔 테리어</option>
                <option value="Maltese">말티즈</option>
                <option value="Pomeranian">포메라니안</option>
                <option value="Crossbreeds">혼종</option>
              </optgroup>
            </select>
          </label>
        </p>

        <p>
          <label for="id_gender">성별 :</label>
          <label id="id_gender"><input type="radio" name="gender" maxlength="15" required="" value="Male" />수<input type="radio" name="gender" maxlength="15" required="" value="Female" />암</label>
        </p>

        <p>
          <label for="id_neutral">중성화 여부 :</label>
          <input type="checkbox" name="neutral" id="id_neutral" />
        </p>

        <p>
          <label for="id_registernumber">반려견 등록번호 :</label>
          <input class="roundop" type="number" name="registernumber" required="" id="id_registernumber" />
        </p>
        <br />
        <hr />
        <br />
        <h3><i class="fas fa-syringe"></i> 반려견 기본 예방접종</h3>
        <p>&emsp;- 예방접종한 동물병원에 문의하시면 쉽게 알 수 있습니다.</p>
        <br />

        <p>
          <label for="id_dhppl">DHPPL :</label>
          <input class="roundop" type="date" name="dhppl" id="id_dhppl" />
        </p>

        <p>
          <label for="id_corona">코로나 :</label>
          <input class="roundop" type="date" name="corona" id="id_corona" />
        </p>

        <p>
          <label for="id_kennel">켄넬 :</label>
          <input class="roundop" type="date" name="kennel" id="id_kennel" />
        </p>

        <p>
          <label for="id_rabies">광견병 :</label>
          <input class="roundop" type="date" name="rabies" id="id_rabies" />
        </p>

        <p>
          <label for="id_heartworm">심장사상충 :</label>
          <input class="roundop" type="date" name="heartworm" id="id_heartworm" />
        </p>

        {% csrf_token %}
        <div align="center">
          <br /><button type="submit" class="btn raise"><i class="far fa-check-square"></i> 입력 완료</button>&emsp;
          <button type="reset" class="btn raise" style="color: red"><i class="far fa-window-close"></i> 다시 작성</button>
        </div>
        <br />
      </form>
      <br />
    </div>
    <div class="com-md-2"></div>
  </div>
{% endblock %}