cart/urls.py
from django.urls import path
from cart.views import *

app_name = "cart"

urlpatterns = [
    path("", detail, name="detail"),
    path("add/<int:product_id>", add, name="product_add"),
    path("remove/<product_id>", remove, name="product_remove"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("accounts/", include("allauth.urls")),
    path("dogs/", include("dogs.urls")),
    path("photo/", include("photo.urls")),
    path("shop/", include("shop.urls")),
    path("shop/cart", include("cart.urls")),
    path("shop/coupon/", include("coupon.urls")),
    path("shop/order/", include("order.urls")),
]

order/urls.py
from django.urls import path
from order.views import *

app_name = "orders"

urlpatterns = [
    path("create/", order_create, name="order_create"),
    path("create_ajax/", OrderCreateAjaxView.as_view(), name="order_create_ajax"),
    path("checkout/", OrderCheckoutAjaxView.as_view(), name="order_checkout"),
    path("validation/", OrderImpAjaxView.as_view(), name="order_validation"),
    path("complete/", order_complete, name="order_complete"),
    path("admin/order//<int:order_id>/", admin_order_detail, name="admin_order_detail"),
    # path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path, re_path
from .views import *

app_name = "shop"

urlpatterns = [
    path("", product_in_category, name="product_all"),
    # re_path(r'^(?P<category_slug>[^/]+(?u))/$', product_in_category, name='product_in_category'),
    path("<category_slug>/", product_in_category, name="product_in_category"),
    path("<int:id>/<product_slug>/", product_detail, name="product_detail"),
    path("my/orders/", myorders, name="myorders"),
]

order/models.py
from datetime import date

from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
from coupon.models import Coupon


class Order(models.Model):
    orderuser = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="orderuser", blank=True
    )

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    coupon = models.ForeignKey(
        Coupon,
        on_delete=models.PROTECT,
        related_name="order_coupon",
        null=True,
        blank=True,
    )
    discount = models.IntegerField(
        default=0, validators=[MinValueValidator(0), MaxValueValidator(100000)]
    )

    shipping = models.IntegerField(null=True, default=1)

    phone = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return "Order {}".format(self.id)

    def get_total_product(self):
        return sum(item.get_item_price() for item in self.items.all())

    def get_total_price(self):
        total_product = self.get_total_product()
        return total_product - self.discount


from shop.models import Product


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="items")
    product = models.ForeignKey(
        Product, on_delete=models.PROTECT, related_name="order_products"
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return "{}".format(self.id)

    def get_item_price(self):
        return self.price * self.quantity


import hashlib
from .iamport import payments_prepare, find_transaction


class OrderTransactionManager(models.Manager):
    def create_new(self, order, amount, success=None, transaction_status=None):
        if not order:
            raise ValueError("주문 오류 this")

        order_hash = hashlib.sha1(str(order.id).encode("utf-8")).hexdigest()
        email_hash = str(order.email).split("@")[0]
        final_hash = hashlib.sha1(
            (order_hash + email_hash).encode("utf-8")
        ).hexdigest()[:10]
        merchant_order_id = "%s" % (final_hash)

        payments_prepare(merchant_order_id, amount)

        transaction = self.model(
            order=order,
            merchant_order_id=merchant_order_id + str(date.today()),
            amount=amount,
        )

        if success is not None:
            transaction.success = success
            transaction.transaction_status = transaction_status

        try:
            transaction.save()
        except Exception as e:
            print("save error", e)

        return transaction.merchant_order_id

    def get_transaction(self, merchant_order_id):
        result = find_transaction(merchant_order_id)
        if result["status"] == "paid":
            return result
        else:
            return None


class OrderTransaction(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    merchant_order_id = models.CharField(max_length=120, null=True, blank=True)
    transaction_id = models.CharField(max_length=120, null=True, blank=True)
    amount = models.PositiveIntegerField(default=0)
    transaction_status = models.CharField(max_length=220, null=True, blank=True)
    type = models.CharField(max_length=120, blank=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)

    objects = OrderTransactionManager()

    def __str__(self):
        return str(self.order.id)

    class Meta:
        ordering = ["-created"]


def order_payment_validation(sender, instance, created, *args, **kwargs):
    if instance.transaction_id:
        print(instance.merchant_order_id, "IMPORT")
        import_transaction = OrderTransaction.objects.get_transaction(
            merchant_order_id=instance.merchant_order_id
        )

        merchant_order_id = import_transaction["merchant_order_id"]
        imp_id = import_transaction["imp_id"]
        amount = import_transaction["amount"]

        print(merchant_order_id, "LOCAL")
        local_transaction = OrderTransaction.objects.filter(
            merchant_order_id=merchant_order_id, transaction_id=imp_id, amount=amount
        ).exists()
        if not import_transaction or not local_transaction:
            raise ValueError("비정상 거래입니다.")

    # 결제 정보가 생성된 후에 호출할 함수를 연결해준다.
    from django.db.models.signals import post_save

    post_save.connect(order_payment_validation, sender=OrderTransaction)

order/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            "orderuser",
            "first_name",
            "last_name",
            "email",
            "address",
            "postal_code",
            "city",
            "phone",
        ]

order/views.py
from django.shortcuts import render, get_object_or_404
from order.models import *
from cart.cart import Cart
from order.forms import *
from django.views.generic.base import View
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required


@login_required
def order_create(request):
    cart = Cart(request)
    if request.method == "POST":
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.amount
                order.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item["product"],
                    price=item["price"],
                    quantity=item["quantity"],
                )

            cart.clear()
            return render(request, "order/created.html", {"order": order})
    else:
        form = OrderCreateForm()
    return render(request, "order/create.html", {"cart": cart, "form": form})


# ajax로 결제 후에 보여줄 결제 완료 화면
def order_complete(request):
    order_id = request.GET.get("order_id")
    order = Order.objects.get(id=order_id)
    return render(request, "order/created.html", {"order": order})


class OrderCreateAjaxView(View):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({"authenticated": False}, status=403)

        cart = Cart(request)
        form = OrderCreateForm(request.POST)

        if form.is_valid():
            order = form.save(commit=False)
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.amount
            order = form.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item["product"],
                    price=item["price"],
                    quantity=item["quantity"],
                )
            cart.clear()
            data = {"order_id": order.id}
            return JsonResponse(data)
        else:
            return JsonResponse({}, status=401)


# 결제 정보 생성
class OrderCheckoutAjaxView(View):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({"authenticated": False}, status=403)

        order_id = request.POST.get("order_id")
        order = Order.objects.get(id=order_id)
        amount = request.POST.get("amount")

        try:
            merchant_order_id = OrderTransaction.objects.create_new(
                order=order, amount=amount
            )
        except Exception as e:
            print(e, 11)
            merchant_order_id = None

        if merchant_order_id is not None:
            data = {"works": True, "merchant_id": merchant_order_id}
            print(merchant_order_id, 111)
            return JsonResponse(data)
        else:
            return JsonResponse({}, status=401)


# 실제 결제가 이뤄진 것이 있는지 확인
class OrderImpAjaxView(View):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({"authenticated": False}, status=403)

        order_id = request.POST.get("order_id")
        order = Order.objects.get(id=order_id)
        merchant_id = request.POST.get("merchant_id")
        imp_id = request.POST.get("imp_id")
        amount = request.POST.get("amount")
        print(merchant_id, 222)

        try:
            print(merchant_id, 222)
            trans = OrderTransaction.objects.get(
                order=order, merchant_order_id=merchant_id, amount=amount
            )
            print(trans, 222222)
        except Exception as e:
            print(e, 22)
            trans = None

        if trans is not None:
            trans.transaction_id = imp_id
            trans.success = True
            trans.save()
            order.paid = True
            order.save()

            data = {"works": True}

            return JsonResponse(data)
        else:
            return JsonResponse({}, status=401)


from django.contrib.admin.views.decorators import staff_member_required


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, "order/admin/detail.html", {"order": order})

order/templates/order/create.html
{% extends 'shopbase.html' %} {% load humanize %} {% block title %}
  - 주문하기
{% endblock %} {% block script %}
  <script type="text/javascript">
    csrf_token = '{{ csrf_token }}'
    order_create_url = '{% url "orders:order_create_ajax" %}'
    order_checkout_url = '{% url "orders:order_checkout" %}'
    order_validation_url = '{% url "orders:order_validation" %}'
    order_complete_url = '{% url "orders:order_complete" %}'
  </script>
  <!-- <script src="https://cdn.iamport.kr/js/iamport.payment-1.1.5.js" type="text/javascript"></script> -->
  <script src="https://cdn.iamport.kr/js/iamport.payment-1.1.7.js" type="text/javascript"></script>

  {% load static %}
  <script src="{% static 'js/checkout.js' %}" type="text/javascript"></script>
{% endblock %} {% block content %}
  <div class="container">
    <div class="row">
      <div class="col" style="font-family: 'SeoulNamsanM'; font-size: 16px">
        <div class="alert alert-info" role="alert">아래 상품으로 주문을 진행합니다. 상품명과 수량을 "정확히" 확인해주세요.</div>
        <h2 align="center" style="margin: 20px 0 10px; font-weight: 600">주문 상품</h2>
        <ul class="list-group" style="width: 800px; margin-left: auto; margin-right: auto">
          {% for item in cart %}
            <li class="list-group-item">
              <i class="fas fa-balance-scale-right"></i>
              {{ item.product.name }} - {{ item.quantity }}개 //
              <span>{{ item.total_price|floatformat:'0'|intcomma }}</span>원
            </li>
          {% endfor %} {% if cart.coupon %}
            <li class="list-group-item">
              "{{ cart.coupon.code }}" 쿠폰 사용<!-- ({{ cart.coupon.amount }}원 할인) -->
              <span>- {{ cart.get_discount_total|floatformat:'0'|intcomma }}원 할인</span>
            </li>
          {% endif %}
        </ul>

        <div class="alert alert-success" role="alert" align="center" style="margin-bottom: 25px; font-weight: 600">결제 금액 : {{ cart.get_total_price|floatformat:'0'|intcomma }}원</div>

        <div style="
                    background-image: url(https://cdn.pixabay.com/photo/2016/04/12/22/35/watercolour-1325656_960_720.jpg);
                ">
          <br />
          <h1 align="center" style="font-weight: 600">주문자 정보 입력</h1>
          <br />
          <!-- form에 class 추가 -->
          <form action="" method="post" class="order-form" style="margin-left: 350px">
            <p>
              <label for="id_last_name">성 :</label>
              <input style="width: 60px" class="roundop" type="text" name="last_name" maxlength="50" required="" id="id_last_name" />
              <label for="id_first_name">이름 :</label>
              <input class="roundop" style="width: 120px" type="text" name="first_name" maxlength="50" required="" id="id_first_name" />
            </p>
            <p>
              <label for="id_email">Email :</label>
              <input class="roundop" type="email" name="email" maxlength="254" required="" id="id_email" value="{{ request.user.email }}" />
            </p>
            <p>
              <label for="id_phone">전화번호 :</label>
              <input class="roundop" type="tel" name="phone" id="id_phone" />
              <input type="hidden" name="orderuser" id="orderuser_id" value="{{ request.user.id }}" />
              <script src="http://dmaps.daum.net/map_js_init/postcode.v2.js"></script>
              <script>
                function sample6_execDaumPostcode() {
                  new daum.Postcode({
                    oncomplete: function (data) {
                      // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.
                
                      // 각 주소의 노출 규칙에 따라 주소를 조합한다.
                      // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                      var addr = '' // 주소 변수
                      var extraAddr = '' // 참고항목 변수
                
                      //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
                      if (data.userSelectedType === 'R') {
                        // 사용자가 도로명 주소를 선택했을 경우
                        addr = data.roadAddress
                      } else {
                        // 사용자가 지번 주소를 선택했을 경우(J)
                        addr = data.jibunAddress
                      }
                
                      // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.
                      if (data.userSelectedType === 'R') {
                        // 법정동명이 있을 경우 추가한다. (법정리는 제외)
                        // 법정동의 경우 마지막 문자가 "동/로/가"로 끝난다.
                        if (data.bname !== '' && /[동|로|가]$/g.test(data.bname)) {
                          extraAddr += data.bname
                        }
                        // 건물명이 있고, 공동주택일 경우 추가한다.
                        if (data.buildingName !== '' && data.apartment === 'Y') {
                          extraAddr += extraAddr !== '' ? ', ' + data.buildingName : data.buildingName
                        }
                        // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.
                        if (extraAddr !== '') {
                          extraAddr = ' (' + extraAddr + ')'
                        }
                        // 조합된 참고항목을 해당 필드에 넣는다.
                        document.getElementById('id_address').value = extraAddr
                      } else {
                        document.getElementById('id_address').value = ''
                      }
                
                      // 우편번호와 주소 정보를 해당 필드에 넣는다.
                      document.getElementById('id_postal_code').value = data.zonecode
                      document.getElementById('id_city').value = addr
                      // 커서를 상세주소 필드로 이동한다.
                      document.getElementById('id_address').focus()
                    }
                  }).open()
                }
              </script>
            </p>

            <p>
              <label for="id_city">주소 :</label>
              <input class="roundop" type="text" name="city" maxlength="100" required="" id="id_city" />
              <input type="button" class="roundop" onclick="sample6_execDaumPostcode()" value="주소 찾기" />
            </p>
            <p>
              <label for="id_address">상세주소 :</label>
              <input class="roundop" type="text" name="address" maxlength="250" required="" id="id_address" />
              <label for="id_postal_code">우편번호 :</label>
              <input class="roundop" type="text" name="postal_code" maxlength="20" required="" id="id_postal_code" />
            </p>

            {% csrf_token %}

            <!-- hidden field 추가 -->
            <input type="hidden" name="pre_order_id" value="0" />
            <input type="hidden" name="amount" value="{{ cart.get_total_price|floatformat:'2' }}" />
            <br />
            <div style="margin-left: 150px">
              <button style="width: 120px; height: 38px" type="submit" class="movebtn"><i class="far fa-arrow-alt-circle-right"></i>주문완료</button>
              <br /><br />
            </div>
          </form>
        </div>
      </div>
    </div>
    <br /><br />
  </div>
  <br />
{% endblock %}

order/templates/order/created.html
{% extends 'shopbase.html' %} {% block title %}
  - 주문완료
{% endblock %} {% block content %}
  <br /><br /><br /><br />
  <div class="container" style="
        background-image: url('https://cdn.pixabay.com/photo/2016/04/12/22/35/watercolour-1325656_960_720.jpg');
        border-radius: 10px;
    ">
    <br /><br /><br /><br /><br /><br />
    <div class="row" style="font-family: 'SeoulNamsanM'; font-size: 16px">
      <i style="font-size: 180px; color: #4b4b4b; margin-left: 30px" class="fas fa-clipboard-check"></i>
      <div class="col">
        <div class="alert alert-success" role="alert" style="line-height: 2em">
          <br />
          <span style="font-weight: 600; font-size: 25px">감사합니다!</span><br />
          주문이 정상적으로 처리되었습니다.<br />
          주문번호는 <strong>{{ order.id }}</strong> 입니다.
          <br />
          주문 내역 확인은
          <a href="{% url 'shop:myorders' %}" style="font-size: 18px">여기서</a>
          해주세요.
          <br />
        </div>
      </div>
    </div>
  </div>
{% endblock %}