cart/urls.py
from django.urls import path
from cart.views import *

app_name = "cart"

urlpatterns = [
    path("", detail, name="detail"),
    path("add/<int:product_id>", add, name="product_add"),
    path("remove/<product_id>", remove, name="product_remove"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("accounts/", include("allauth.urls")),
    path("dogs/", include("dogs.urls")),
    path("photo/", include("photo.urls")),
    path("shop/", include("shop.urls")),
    path("shop/cart", include("cart.urls")),
    path("shop/coupon/", include("coupon.urls")),
    path("shop/order/", include("order.urls")),
]

dogs/urls.py
from django.urls import path, re_path
from dogs.views import *
from dogs.models import *
from django.views.generic.detail import DetailView


app_name = "dogs"

urlpatterns = [
    path("info/", info_list, name="info_list"),
    path("infocreate/", infoCreate.as_view(), name="info_create"),
    path("info/update/<int:pk>/", infoUpdate.as_view(), name="info_update"),
    path("info/delete/<int:pk>/", infoDelete.as_view(), name="info_delete"),
    path("daily/", daily_list, name="daily_list"),
    path("dailycreate/", dailyCreate.as_view(), name="daily_create"),
    path("daily/update/<int:pk>/", dailyUpdate.as_view(), name="daily_update"),
    path("daily/delete/<int:pk>/", dailyDelete.as_view(), name="daily_delete"),
    path("daily/detail/<int:pk>/", dailyDetail.as_view(), name="daily_detail"),
    # re_path(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list_daily'),
    re_path(
        r"^tag/(?P<tag>[^/]+)/$", PostTOL.as_view(), name="tagged_object_list_daily"
    ),
    path("chart/", chartt, name="chart"),
]

photo/urls.py
from django.urls import path, re_path
from photo.views import *
from photo.models import Photo

app_name = "photo"

urlpatterns = [
    path("", photo_list, name="photo_list"),
    path("detail/<int:pk>/", PhotoDetailView.as_view(), name="photo_detail"),
    path("upload/", PhotoUploadView.as_view(), name="photo_upload"),
    path("delete/<int:pk>/", PhotoDeleteView.as_view(), name="photo_delete"),
    path("update/<int:pk>/", PhotoUpdateView.as_view(), name="photo_update"),
    re_path(r"^like/$", post_like, name="post_like"),
    # re_path(r"^tag/(?P<tag>[^/]+(?u))/$", PostTOL.as_view(), name="tagged_object_list"),
    re_path(r"^tag/(?P<tag>[^/]+)/$", PostTOL.as_view(), name="tagged_object_list"),
]

shop/urls.py
from django.urls import path, re_path
from .views import *

app_name = "shop"

urlpatterns = [
    path("", product_in_category, name="product_all"),
    # re_path(r'^(?P<category_slug>[^/]+(?u))/$', product_in_category, name='product_in_category'),
    path("<category_slug>/", product_in_category, name="product_in_category"),
    path("<int:id>/<product_slug>/", product_detail, name="product_detail"),
    path("my/orders/", myorders, name="myorders"),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewpoint" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>
      MY DOGS{% block title %}

      {% endblock %}
    </title>

    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/bd27b9be04.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Libre+Baskerville|Roboto+Mono|Raleway|Noto+Sans+KR|Poor+Story|Gaegu|Nanum+Gothic|Jua&display|Poppin=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
    <script src="https://unpkg.com/nprogress@0.2.0/nprogress.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/nprogress@0.2.0/nprogress.css" />
    {% load static %} {% block script %}

    {% endblock %}
    {% comment %} <link rel="stylesheet" href="https://mydogs-s3.s3.ap-northeast-2.amazonaws.com/static/css/baseM.css?versionId=null" /> {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/baseM.css' %}" />

    {% block css %}

    {% endblock %}

    <style></style>
  </head>
  <body class="paper">
    <script>
      NProgress.configure({ showSpinner: false })
      
      NProgress.start()
      
      NProgress.inc()
      
      NProgress.done()
    </script>

    <div class="container">
      <header id="header_fix" class="header clearfix">
        <nav class="navbar navbar-expand-lg" style="
                        font-family: 'Raleway', sans-serif;
                        font-weight: Semi-Bold;
                    ">
          <a class="navbar-brand" href="/" style="color: #ffffff; text-decoration: none">My DOGS</a>
          <ul id="ul_top" class="nav">
            <li>
              <a href="/" id="green" style="color: #ffffff; text-decoration: none">HOME</a>
            </li>
            {% if user.is_authenticated %}
              <li class="dropdown">
                <a href="javascript:void()" class="dropbtn" style="color: #ffffff; text-decoration: none">Welcome, {{ user.get_username }}</a>
                <div class="dropdown-content" style="
                                    font-family: 'Noto Sans KR', sans-serif;
                                    font-weight: Thin;
                                ">
                  <a href="{% url 'account_change_password' %}"><i class="fas fa-key"></i> 비밀번호 변경</a>
                  <a href="{% url 'account_email' %}"><i class="fas fa-envelope"></i> 이메일 관리</a>
                </div>
              </li>&nbsp; &nbsp;<li class="dropdown">
                <a href="javascript:void()" class="dropbtn" style="color: #ffffff; text-decoration: none">MyDOG</a>
                <div class="dropdown-content" style="
                                    font-family: 'Noto Sans KR', sans-serif;
                                    font-weight: Thin;
                                ">
                  <a href="{% url 'dogs:info_list' %}"><i class="fas fa-info-circle"></i> 기본 정보</a>
                  <a href="{% url 'dogs:daily_list' %}"><i class="fas fa-book-open"></i> 일일 기록</a>
                  <a href="{% url 'dogs:chart' %}"><i class="fas fa-chart-line"></i> 분석</a>
                </div>
              </li>&nbsp; &nbsp;<li class="dropdown">
                <a href="javascript:void()" class="dropbtn" style="color: #ffffff; text-decoration: none">DogPIC</a>
                <div class="dropdown-content" style="
                                    font-family: 'Noto Sans KR', sans-serif;
                                    font-weight: Thin;
                                ">
                  <a href="{% url 'photo:photo_upload' %}"><i class="fas fa-camera-retro"></i> 사진 올리기</a>
                  <a href="{% url 'photo:photo_list' %}"><i class="fas fa-images"></i> 게시글 보기</a>
                </div>
              </li>

              <li>
                <a href="{% url 'shop:product_all' %}" style="color: #ffffff; text-decoration: none">SHOP</a>
              </li>
              <li>
                <a href="{% url 'account_logout' %}" style="color: #ffffff; text-decoration: none">Logout</a>
              </li>
            {% else %}
              <li>
                <a href="{% url 'account_login' %}" style="color: #ffffff; text-decoration: none">Login</a>
              </li>
              <li>
                <a href="{% url 'account_signup' %}" style="color: #ffffff; text-decoration: none">Signup</a>
              </li>
            {% endif %} {% block cart %}

            {% endblock %}
          </ul>
        </nav>
      </header>

      {% block slide %}

      {% endblock %} {% block content %}

      {% endblock %}
      {% block pagination %}

      {% endblock %}

      <footer id="footer">
        <div class="container">
          <div class="row">
            <div class="col-sm-6">&copy; 2020 Lee Dong Ju. all rights reserved.</div>
            <div class="col-sm-6">
              <ul class="social-icons">
                <li>
                  <a href="https://github.com/dongju93" target="_blank"><i class="fab fa-facebook"></i></a>
                </li>
                <li>
                  <a href="https://github.com/dongju93" target="_blank"><i class="fab fa-twitter"></i></a>
                </li>
                <li>
                  <a href="https://github.com/dongju93" target="_blank"><i class="fab fa-google-plus"></i></a>
                </li>
                <li>
                  <a href="https://github.com/dongju93" target="_blank"><i class="fab fa-linkedin"></i></a>
                </li>
                <li>
                  <a href="https://github.com/dongju93" target="_blank"><i class="fab fa-youtube"></i></a>
                </li>
                <li>
                  <a href="https://github.com/dongju93" target="_blank"><i class="fab fa-github"></i></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
      <!-- /#footer -->
    </div>
  </body>
</html>

templates/shopbase.html
{% extends 'base.html' %} {% load humanize %} {% block script %}

{% endblock %}
{% block cart %}
  <li>
    <a href="{% url 'cart:detail' %}" class="roundop" style="color: #000000; text-decoration: none">
      <i class="fas fa-shopping-cart"></i> CART{% if (cart|length) > 0 %}
        {{ cart.get_total_price|floatformat:'0'|intcomma }}원 / {{ cart|length }}개
      {% else %}
        : Empty
      {% endif %}
    </a>
  </li>
{% endblock %}